# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  purge_expired_data_exports:
    command: "DataExport.purge_expired"
    schedule: every hour at minute 27
  close_inactive_support_conversations:
    command: "Chat.close_inactive_support_conversations"
    schedule: every hour at minute 8
  purge_expired_visits:
    command: "Ahoy::Visit.purge_expired"
    schedule: every day at 4am
  purge_unconfirmed_users:
    command: "User.purge_unconfirmed"
    schedule: every day at 5am
